service: spreent
image: denfrac/spreent
servers:
  web:
    - spreent.ca

proxy:
  ssl: true
  hosts:
    - spreent.ca
    - www.spreent.ca

registry:
  username: denfrac
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
    - SENDGRID_API_KEY
    - DO_SPACES_ACCESS_KEY
    - DO_SPACES_SECRET_KEY
    - DO_SPACES_BUCKET
    - DO_SPACES_REGION
    - RECAPTCHA_SITE_KEY
    - RECAPTCHA_SECRET_KEY
    - KAMAL_REGISTRY_PASSWORD
    - REDIS_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    DB_HOST: spreent-db
    RAILS_LOG_LEVEL: debug

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "spreent_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

accessories:
   db:
     image: mysql:8.0
     host: spreent.ca
     port: "127.0.0.1:3306:3306"
     env:
       clear:
         MYSQL_ROOT_HOST: '%'
       secret:
         - MYSQL_ROOT_PASSWORD
     files:
       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
     directories:
       - data:/var/lib/mysql
   redis:
      image: redis:7.0
      host: spreent.ca
      port: 6379
      env:
        clear:
          REDIS_MAXMEMORY: 256mb
        secret:
          - REDIS_PASSWORD
      files:
        - config/redis.conf:/usr/local/etc/redis/redis.conf
      cmd: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - /var/lib/redis:/data