name: Kamal Deploy

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      deployed_version:
        description: "The deployed version (short commit hash)"
        value: ${{ jobs.deploy.outputs.deployed_version }}
      deployed_by:
        description: "The user who triggered the deployment"
        value: ${{ jobs.deploy.outputs.deployed_by }}
      deployment_time:
        description: "The time of deployment"
        value: ${{ jobs.deploy.outputs.deployment_time }}
    secrets:
      RAILS_MASTER_KEY:
        required: true
      DO_SPACES_ACCESS_KEY:
        required: true
      DO_SPACES_SECRET_KEY:
        required: true
      DO_SPACES_BUCKET:
        required: true
      DO_SPACES_REGION:
        required: true
      KAMAL_REGISTRY_USERNAME:
        required: true
      KAMAL_REGISTRY_PASSWORD:
        required: true
      SERVER_IP:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      MYSQL_ROOT_PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy with Kamal
    runs-on: ubuntu-latest
    outputs:
      deployed_version: ${{ steps.deployment_info.outputs.deployed_version }}
      deployed_by: ${{ steps.deployment_info.outputs.deployed_by }}
      deployment_time: ${{ steps.deployment_info.outputs.deployment_time }}

    env:
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      KAMAL_REGISTRY_USERNAME: ${{ secrets.KAMAL_REGISTRY_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      DO_SPACES_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
      DO_SPACES_SECRET_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
      DO_SPACES_BUCKET: ${{ secrets.DO_SPACES_BUCKET }}
      DO_SPACES_REGION: ${{ secrets.DO_SPACES_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
          bundler-cache: true

      - name: Install Kamal
        run: gem install kamal

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Known Hosts
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa spreent.ca >> ~/.ssh/known_hosts

      - name: Build and deploy with Kamal
        run: |
          kamal deploy --version ${GITHUB_SHA::8}
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DO_SPACES_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
          DO_SPACES_SECRET_KEY: ${{ secrets.DO_SPACES_SECRET_KEY }}
          DO_SPACES_BUCKET: ${{ secrets.DO_SPACES_BUCKET }}
          DO_SPACES_REGION: ${{ secrets.DO_SPACES_REGION }}

      - name: Store deployment details
        id: deployment_info
        if: success()
        run: |
          echo "deployed_version=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "deployed_by=${{ github.actor }}" >> $GITHUB_OUTPUT
          echo "deployment_time=$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT